from __future__ import annotations

from collections import defaultdict

from .docs_common import read_title, write_if_changed
from .project_paths import DOCSRC_LIBRARY, DOCSRC_NOTE

type DocEntry = tuple[str, str]
type GroupedDocEntries = list[tuple[str, list[DocEntry]]]


def build_library_sections(lib_header: str, verifies: list[tuple[str, str]]) -> str:
    """Build managed sections for a library page."""
    lines: list[str] = []

    if verifies:
        lines.extend(["## Verify", ""])
        for title, doc_path in verifies:
            lines.append(f"- [{title}](../../verify/{doc_path})")
        lines.append("")

    lines.extend(
        [
            "## Code",
            "",
            "```cpp",
            f'--8<-- "include/{lib_header}"',
            "```",
            "",
            "## Bundled",
            "",
            "```cpp",
            f'--8<-- "bundled/{lib_header}"',
            "```",
        ]
    )
    return "\n".join(lines)


def strip_managed_library_sections(markdown: str, lib_header: str) -> str:
    """Strip managed Code/Bundled sections from a library page."""
    body = markdown.rstrip()
    for bundled_heading in ("## Bundled", "## Bundled (Copy & Paste)"):
        managed_tail = "\n".join(
            [
                "## Code",
                "",
                "```cpp",
                f'--8<-- "include/{lib_header}"',
                "```",
                "",
                bundled_heading,
                "",
                "```cpp",
                f'--8<-- "bundled/{lib_header}"',
                "```",
            ]
        )
        if body.endswith(managed_tail):
            return body[: -len(managed_tail)].rstrip()
    return body


def scan_library_docs() -> tuple[GroupedDocEntries, dict[str, str]]:
    """Scan docsrc/library/ for .md files and build navigation groups and title map."""
    groups: dict[str, list[DocEntry]] = defaultdict(list)
    titles: dict[str, str] = {}

    for md_path in sorted(DOCSRC_LIBRARY.rglob("*.md")):
        if md_path.name == "index.md":
            continue
        rel = md_path.relative_to(DOCSRC_LIBRARY)
        if len(rel.parts) != 2:
            continue

        category_name = rel.parts[0].replace("_", " ").title()
        title = read_title(md_path)
        doc_path = f"library/{rel.as_posix()}"

        groups[category_name].append((title, doc_path))
        titles[rel.with_suffix(".hpp").as_posix()] = title

    for entries in groups.values():
        entries.sort(key=lambda entry: entry[0].casefold())

    return sorted(groups.items()), titles


def build_library_nav(groups: GroupedDocEntries) -> list:
    nav: list = [{"Library Top": "library/index.md"}]
    for category_name, entries in groups:
        nav.append({category_name: [{title: doc_path} for title, doc_path in entries]})
    return nav


def generate_library_index(
    groups: GroupedDocEntries,
    generator_name: str = "scripts/mkdocs_hooks.py",
) -> None:
    lines = [
        "# Library Top",
        "",
        "ライブラリ実装の一覧ページです。",
        "",
        f"<!-- This file is auto-generated by {generator_name} -->",
        "",
    ]
    for category_name, entries in groups:
        lines.append(f"## {category_name}")
        lines.append("")
        for title, doc_path in entries:
            lines.append(f"- [{title}]({doc_path.removeprefix('library/')})")
        lines.append("")

    write_if_changed(DOCSRC_LIBRARY / "index.md", "\n".join(lines).rstrip() + "\n")


def scan_note_docs() -> list[DocEntry]:
    entries: list[DocEntry] = []
    for md_path in sorted(DOCSRC_NOTE.glob("*.md")):
        if md_path.name == "index.md":
            continue
        entries.append((read_title(md_path), f"note/{md_path.name}"))
    return entries


def build_note_nav(entries: list[DocEntry]) -> list:
    nav: list = [{"Note Top": "note/index.md"}]
    for title, doc_path in entries:
        nav.append({title: doc_path})
    return nav


def generate_note_index(
    entries: list[DocEntry],
    generator_name: str = "scripts/mkdocs_hooks.py",
) -> None:
    lines = [
        "# Note",
        "",
        "いろいろメモ　旧scrapboxに書いてた内容を引っ越し予定",
        "",
        f"<!-- This file is auto-generated by {generator_name} -->",
        "",
    ]
    for title, doc_path in entries:
        lines.append(f"- [{title}]({doc_path.removeprefix('note/')})")
    lines.append("")

    write_if_changed(DOCSRC_NOTE / "index.md", "\n".join(lines).rstrip() + "\n")
