from __future__ import annotations

from collections import defaultdict
from pathlib import Path

from .docs_common import write_if_changed
from .project_paths import DOCSRC, ROOT
from .verify_data import compute_hash, detect_libraries, load_judge_display_names


def _entry_title(key: str, entry: dict) -> str:
    return entry.get("title", Path(key).stem.replace("_", " ").title())


def _verify_doc_path(key: str) -> str:
    return key.removeprefix("verify/").replace(".cpp", ".md")


def _judge_category(key: str) -> str:
    parts = key.removeprefix("verify/").split("/")
    if len(parts) >= 2:
        name = parts[0]
        return load_judge_display_names().get(name, name.replace("_", " ").title())
    return "Other"


def build_verify_nav(status: dict) -> list:
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for key, entry in sorted(status.items()):
        groups[_judge_category(key)].append((_entry_title(key, entry), "verify/" + _verify_doc_path(key)))

    nav: list = [{"Verify Top": "verify/index.md"}]
    for group_name, entries in sorted(groups.items()):
        nav.append({group_name: [{title: doc_path} for title, doc_path in entries]})
    return nav


def _resolve_libraries(verify_path: Path, parent_of: dict[str, str] | None) -> list[str]:
    libraries = detect_libraries(verify_path) if verify_path.exists() else []
    if not parent_of:
        return libraries
    seen: set[str] = set()
    resolved: list[str] = []
    for lib in libraries:
        canonical = parent_of.get(lib, lib)
        if canonical in seen:
            continue
        seen.add(canonical)
        resolved.append(canonical)
    return resolved


def generate_verify_pages(
    status: dict,
    library_titles: dict[str, str],
    parent_of: dict[str, str] | None = None,
    generator_name: str = "scripts/mkdocs_hooks.py",
) -> None:
    for key, entry in status.items():
        verify_path = Path(key)
        out_path = DOCSRC / "verify" / _verify_doc_path(key)
        title = _entry_title(key, entry)
        judge_url = entry.get("judge_url", "")
        cpp_path = ROOT / key
        libraries = _resolve_libraries(cpp_path, parent_of)

        lines = [
            f"# {title}",
            "",
            f"<!-- This file is auto-generated by {generator_name} -->",
            "",
        ]

        if libraries:
            lines.extend(["## Target Library", ""])
            for lib in libraries:
                lib_name = library_titles.get(lib, Path(lib).stem.replace("_", " ").title())
                lines.append(f"- [{lib_name}](../../library/{lib.replace('.hpp', '.md')})")
            lines.append("")

        if judge_url:
            lines.extend(["## Judge", "", f"- [{title}]({judge_url})", ""])

        lines.extend(
            [
                "## Verify Code",
                "",
                f"Source: `{key}`",
                "",
                "```cpp",
                f'--8<-- "bundled/{key}"',
                "```",
            ]
        )

        write_if_changed(out_path, "\n".join(lines).rstrip() + "\n")


def generate_verify_index(status: dict, generator_name: str = "scripts/mkdocs_hooks.py") -> None:
    groups: dict[str, list[tuple[str, str, dict]]] = defaultdict(list)
    for key, entry in sorted(status.items()):
        groups[_judge_category(key)].append((_entry_title(key, entry), _verify_doc_path(key), entry))

    lines = [
        "# Verify Top",
        "",
        f"<!-- This file is auto-generated by {generator_name} -->",
        "",
    ]

    stale_entries: list[tuple[str, str, str]] = []
    grouped_lines: dict[str, list[str]] = {}

    for group_name, entries in sorted(groups.items()):
        group_lines: list[str] = []
        for title, doc_path, entry in entries:
            cpp_path = ROOT / ("verify/" + doc_path.replace(".md", ".cpp"))
            if not cpp_path.exists():
                group_lines.append(f"- ❓ [{title}]({doc_path})")
                continue

            current_hash = compute_hash(cpp_path)
            date = entry.get("verified_at", "")[:10]
            if entry.get("bundled_hash") == current_hash:
                group_lines.append(f"- ✅ [{title}]({doc_path}) — {date}")
            else:
                stale_entries.append((title, doc_path, date))
        grouped_lines[group_name] = group_lines

    if stale_entries:
        lines.extend(["## Stale", ""])
        for title, doc_path, date in stale_entries:
            lines.append(f"- ⚠️ [{title}]({doc_path}) — {date}")
        lines.append("")

    for group_name, group_lines in grouped_lines.items():
        if not group_lines:
            continue
        lines.extend([f"## {group_name}", ""])
        lines.extend(group_lines)
        lines.append("")

    write_if_changed(DOCSRC / "verify" / "index.md", "\n".join(lines).rstrip() + "\n")


def build_verify_map(
    status: dict,
    parent_of: dict[str, str] | None = None,
) -> dict[str, list[tuple[str, str]]]:
    lib_to_verifies: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for key, entry in sorted(status.items()):
        cpp_path = ROOT / key
        libraries = _resolve_libraries(cpp_path, parent_of)
        for lib in libraries:
            lib_to_verifies[lib].append((_entry_title(key, entry), _verify_doc_path(key)))
    return lib_to_verifies
