from __future__ import annotations

import hashlib
import json
import sys
from collections import defaultdict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INCLUDE_ROOT = ROOT / "include"
BUNDLE_ROOT = ROOT / "bundled"
VERIFY_ROOT = ROOT / "verify"
DOCSRC = ROOT / "docsrc"
STATUS_PATH = VERIFY_ROOT / "status.json"

_SCRIPTS_DIR = str(ROOT / "scripts")
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)

import re

from bundle_header import bundle_header, bundle_header_to_string  # noqa: E402
from sync_library_index import sync_library_index  # noqa: E402

_INCLUDE_RE = re.compile(r'^\s*#\s*include\s*"([^"]+)"\s*$')


def _detect_libraries(verify_path: Path) -> list[str]:
    """Parse verify .cpp to find library headers it includes."""
    libs: list[str] = []
    for line in verify_path.read_text(encoding="utf-8").splitlines():
        m = _INCLUDE_RE.match(line)
        if m and (INCLUDE_ROOT / m.group(1)).exists():
            libs.append(m.group(1))
    return libs


def _load_status() -> dict:
    if STATUS_PATH.exists():
        return json.loads(STATUS_PATH.read_text(encoding="utf-8"))
    return {}


def _compute_verify_hash(verify_path: Path) -> str:
    include_dirs = [INCLUDE_ROOT.resolve(), VERIFY_ROOT.resolve(), ROOT.resolve()]
    text = bundle_header_to_string(verify_path, include_dirs, ROOT)
    return "sha256:" + hashlib.sha256(text.encode("utf-8")).hexdigest()


def _judge_category(key: str) -> str:
    """Derive judge category from verify key: 'verify/library_checker/foo.cpp' → 'Library Checker'."""
    parts = key.removeprefix("verify/").split("/")
    if len(parts) >= 2:
        return parts[0].replace("_", " ").title()
    return "Other"


def _write_if_changed(path: Path, text: str) -> None:
    if path.exists() and path.read_text(encoding="utf-8") == text:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def _generate_verify_pages(status: dict) -> None:
    """Auto-generate individual verify .md pages from status.json."""
    for key, entry in status.items():
        # key: "verify/library_checker/lowest_common_ancestor.cpp"
        verify_path = Path(key)
        doc_rel = str(verify_path.relative_to("verify")).replace(".cpp", ".md")
        out_path = DOCSRC / "verify" / doc_rel

        title = entry.get("title", verify_path.stem.replace("_", " ").title())
        judge_url = entry.get("judge_url", "")
        cpp_path = ROOT / key
        libraries = _detect_libraries(cpp_path) if cpp_path.exists() else []

        lines = [
            f"# {title}",
            "",
            "<!-- This file is auto-generated by scripts/mkdocs_hooks.py -->",
            "",
        ]

        if libraries:
            lines.append("## Target Library")
            lines.append("")
            for lib in libraries:
                lib_name = Path(lib).stem.replace("_", " ").title()
                lib_doc = f"../../library/{lib.replace('.hpp', '.md')}"
                lines.append(f"- [{lib_name}]({lib_doc})")
            lines.append("")

        if judge_url:
            lines.append("## Judge")
            lines.append("")
            lines.append(f"- [{title}]({judge_url})")
            lines.append("")

        lines.append("## Verify Code")
        lines.append("")
        bundled_rel = f"bundled/{key}"
        lines.append(f"Source: `{key}`")
        lines.append("")
        lines.append("```cpp")
        lines.append(f'--8<-- "{bundled_rel}"')
        lines.append("```")

        _write_if_changed(out_path, "\n".join(lines).rstrip() + "\n")


def _generate_verify_index(status: dict) -> None:
    """Auto-generate docsrc/verify/index.md with staleness status."""
    # Group entries by judge
    groups: dict[str, list[tuple[str, str, dict]]] = defaultdict(list)
    for key, entry in sorted(status.items()):
        category = _judge_category(key)
        doc_path = key.removeprefix("verify/").replace(".cpp", ".md")
        title = entry.get("title", Path(key).stem.replace("_", " ").title())
        groups[category].append((title, doc_path, entry))

    lines = [
        "# Verify Top",
        "",
        "<!-- This file is auto-generated by scripts/mkdocs_hooks.py -->",
        "",
    ]

    for group_name, entries in sorted(groups.items()):
        lines.append(f"## {group_name}")
        lines.append("")
        for title, doc_path, entry in entries:
            cpp_rel = "verify/" + doc_path.replace(".md", ".cpp")
            cpp_path = ROOT / cpp_rel

            if cpp_path.exists():
                current_hash = _compute_verify_hash(cpp_path)
                date = entry.get("verified_at", "")[:10]
                if entry.get("bundled_hash") == current_hash:
                    lines.append(f"- ✅ [{title}]({doc_path}) — {date}")
                else:
                    lines.append(f"- ⚠️ [{title}]({doc_path}) — STALE ({date})")
            else:
                lines.append(f"- ❓ [{title}]({doc_path})")
        lines.append("")

    _write_if_changed(DOCSRC / "verify" / "index.md", "\n".join(lines).rstrip() + "\n")


def _build_verify_nav(status: dict) -> list:
    """Build Verify nav entries from status.json."""
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for key, entry in sorted(status.items()):
        category = _judge_category(key)
        title = entry.get("title", Path(key).stem.replace("_", " ").title())
        doc_path = "verify/" + key.removeprefix("verify/").replace(".cpp", ".md")
        groups[category].append((title, doc_path))

    nav: list = [{"Verify Top": "verify/index.md"}]
    for group_name, entries in sorted(groups.items()):
        nav.append({group_name: [{t: p} for t, p in entries]})
    return nav


def on_config(config):
    """Inject Verify nav from status.json into mkdocs config."""
    status = _load_status()
    if not status:
        return config

    verify_nav = _build_verify_nav(status)
    for item in config["nav"]:
        if isinstance(item, dict) and "Verify" in item:
            item["Verify"] = verify_nav
            break

    return config


def _build_verify_map(status: dict) -> dict[str, list[tuple[str, str]]]:
    """Build library → [(verify_title, verify_doc_path)] mapping from actual .cpp files."""
    lib_to_verifies: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for key, entry in sorted(status.items()):
        title = entry.get("title", Path(key).stem.replace("_", " ").title())
        verify_doc = key.removeprefix("verify/").replace(".cpp", ".md")
        cpp_path = ROOT / key
        libraries = _detect_libraries(cpp_path) if cpp_path.exists() else []
        for lib in libraries:
            lib_to_verifies[lib].append((title, verify_doc))
    return lib_to_verifies


def _update_library_verify_sections(status: dict) -> None:
    """Update ## Verify sections in library .md pages from status.json."""
    verify_map = _build_verify_map(status)

    for lib_header, verifies in verify_map.items():
        # lib_header: "tree/lowest_common_ancestor.hpp"
        lib_doc = DOCSRC / "library" / lib_header.replace(".hpp", ".md")
        if not lib_doc.exists():
            continue

        text = lib_doc.read_text(encoding="utf-8")

        # Build new Verify section content
        verify_lines = ["## Verify", ""]
        for v_title, v_doc in verifies:
            verify_lines.append(f"- [{v_title}](../../verify/{v_doc})")
        new_section = "\n".join(verify_lines)

        # Replace existing ## Verify section (up to next ## or end of file)
        pattern = r"## Verify\n(?:.*?)(?=\n## |\Z)"
        new_text = re.sub(pattern, new_section + "\n", text, count=1, flags=re.DOTALL)

        _write_if_changed(lib_doc, new_text)


def on_pre_build(config):
    sync_library_index(write=True)

    for path in INCLUDE_ROOT.rglob("*.hpp"):
        rel = path.relative_to(INCLUDE_ROOT)
        out_path = BUNDLE_ROOT / rel
        bundle_header(path, out_path, include_dirs=[INCLUDE_ROOT])
    for path in VERIFY_ROOT.rglob("*.cpp"):
        rel = path.relative_to(ROOT)
        out_path = BUNDLE_ROOT / rel
        bundle_header(path, out_path, include_dirs=[INCLUDE_ROOT, VERIFY_ROOT, ROOT])

    status = _load_status()
    _generate_verify_pages(status)
    _generate_verify_index(status)
    _update_library_verify_sections(status)
