#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
from collections import defaultdict
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
LIBRARY_DIR = ROOT / "docsrc" / "library"
LIBRARY_INDEX_MD = LIBRARY_DIR / "index.md"


def scan_library_docs() -> list[tuple[str, list[tuple[str, str]]]]:
    """Scan docsrc/library/ for .md files and build navigation groups."""
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for md_path in sorted(LIBRARY_DIR.rglob("*.md")):
        if md_path.name == "index.md":
            continue
        rel = md_path.relative_to(LIBRARY_DIR)
        if len(rel.parts) != 2:  # expect category/file.md
            continue
        category_dir = rel.parts[0]
        category_name = category_dir.replace("_", " ").title()

        # Read title from first # heading
        title = rel.stem.replace("_", " ").title()
        for line in md_path.read_text(encoding="utf-8").splitlines():
            if line.startswith("# "):
                title = line[2:].strip()
                break

        groups[category_name].append((title, rel.as_posix()))

    return sorted(groups.items())


def render_library_index(groups: list[tuple[str, list[tuple[str, str]]]]) -> str:
    lines = [
        "# Library Top",
        "",
        "ライブラリ実装の一覧ページです。",
        "",
        "<!-- This file is auto-generated by scripts/mkdocs_hooks.py -->",
        "",
    ]

    for group_name, links in groups:
        lines.append(f"## {group_name}")
        lines.append("")
        for title, path in links:
            lines.append(f"- [{title}]({path})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def sync_library_index(*, write: bool) -> tuple[bool, str, str]:
    expected = render_library_index(scan_library_docs())
    current = LIBRARY_INDEX_MD.read_text(encoding="utf-8") if LIBRARY_INDEX_MD.exists() else ""
    changed = current != expected

    if write and changed:
        LIBRARY_INDEX_MD.parent.mkdir(parents=True, exist_ok=True)
        LIBRARY_INDEX_MD.write_text(expected, encoding="utf-8")

    return changed, current, expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="docsrc/library/index.md を更新する")
    args = parser.parse_args()

    changed, current, expected = sync_library_index(write=args.write)

    if args.write:
        if changed:
            print(f"updated: {LIBRARY_INDEX_MD}")
        else:
            print(f"already up-to-date: {LIBRARY_INDEX_MD}")
        return 0

    if not changed:
        print("OK: docsrc/library/index.md is in sync with filesystem")
        return 0

    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(LIBRARY_INDEX_MD),
        tofile="expected",
    )
    sys.stdout.writelines(diff)
    print("\nERROR: Library Top がファイルシステムと不一致です。")
    print("実行: uv run python scripts/sync_library_index.py --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
