#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
from pathlib import Path
import sys

import yaml


ROOT = Path(__file__).resolve().parents[1]
MKDOCS_YML = ROOT / "mkdocs.yml"
LIBRARY_INDEX_MD = ROOT / "docsrc" / "library" / "index.md"


def load_library_nav_groups() -> list[tuple[str, list[tuple[str, str]]]]:
    config = yaml.safe_load(MKDOCS_YML.read_text(encoding="utf-8"))
    nav = config.get("nav", [])

    library_section = None
    for item in nav:
        if isinstance(item, dict) and "Library" in item:
            library_section = item["Library"]
            break

    if library_section is None:
        raise RuntimeError("mkdocs.yml に Library セクションがありません。")
    if not isinstance(library_section, list):
        raise RuntimeError("mkdocs.yml の Library セクション形式が不正です。")

    groups: list[tuple[str, list[tuple[str, str]]]] = []
    for item in library_section:
        if not isinstance(item, dict) or len(item) != 1:
            continue
        name, value = next(iter(item.items()))
        if name == "Library Top":
            continue
        if not isinstance(value, list):
            continue

        links: list[tuple[str, str]] = []
        for child in value:
            if not isinstance(child, dict) or len(child) != 1:
                continue
            title, path = next(iter(child.items()))
            if not isinstance(path, str):
                continue
            if path.startswith("library/"):
                path = path[len("library/") :]
            links.append((title, path))

        groups.append((name, links))

    return groups


def render_library_index(groups: list[tuple[str, list[tuple[str, str]]]]) -> str:
    lines = [
        "# Library Top",
        "",
        "ライブラリ実装の一覧ページです。",
        "",
        "<!-- This file is auto-generated by scripts/sync_library_index.py -->",
        "",
    ]

    for group_name, links in groups:
        lines.append(f"## {group_name}")
        lines.append("")
        for title, path in links:
            lines.append(f"- [{title}]({path})")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def sync_library_index(*, write: bool) -> tuple[bool, str, str]:
    expected = render_library_index(load_library_nav_groups())
    current = LIBRARY_INDEX_MD.read_text(encoding="utf-8") if LIBRARY_INDEX_MD.exists() else ""
    changed = current != expected

    if write and changed:
        LIBRARY_INDEX_MD.parent.mkdir(parents=True, exist_ok=True)
        LIBRARY_INDEX_MD.write_text(expected, encoding="utf-8")

    return changed, current, expected


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="docsrc/library/index.md を更新する")
    args = parser.parse_args()

    changed, current, expected = sync_library_index(write=args.write)

    if args.write:
        if changed:
            print(f"updated: {LIBRARY_INDEX_MD}")
        else:
            print(f"already up-to-date: {LIBRARY_INDEX_MD}")
        return 0

    if not changed:
        print("OK: docsrc/library/index.md is in sync with mkdocs.yml")
        return 0

    diff = difflib.unified_diff(
        current.splitlines(keepends=True),
        expected.splitlines(keepends=True),
        fromfile=str(LIBRARY_INDEX_MD),
        tofile="expected",
    )
    sys.stdout.writelines(diff)
    print("\nERROR: Library Top が mkdocs.yml と不一致です。")
    print("実行: uv run python scripts/sync_library_index.py --write")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
