name: Build MkDocs into docs/

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install mkdocs-material pymdown-extensions

      - name: Build MkDocs to docs/
        run: mkdocs build --clean --site-dir docs

      - name: Commit built site
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs
          git commit -m "Auto-build site" || echo "No changes to commit"
          git push
